// Generated by `wit-bindgen` 0.46.0. DO NOT EDIT!
#ifndef __CPP_GUEST_BINDINGS_APPLICATION_H
#define __CPP_GUEST_BINDINGS_APPLICATION_H
#include <cstdint>
#include <utility>
namespace exports {
  namespace application {
    int32_t GetCurrentUnixtime();
  }
}

#endif
