// Generated by `wit-bindgen` 0.46.0. DO NOT EDIT!

// Ensure that the *_component_type.o object is linked in
#ifdef __wasm32__
extern "C" void __component_type_object_force_link_application(void);
__attribute__((used))
void __component_type_object_force_link_application_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_application();
}
#endif
#include "application_cpp.h"
#include <cstdlib> // realloc

extern "C" void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size);

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}


extern "C" __attribute__((__export_name__("get-current-unixtime")))
int32_t get_current_unixtime()
{
  auto result0 = exports::application::GetCurrentUnixtime();
  return (int32_t(result0));
}

// Component Adapters
